[package]
name = "rust-lock-owner-column"
version = "0.1.0"
edition = "2021"
rust-version = "1.97.1"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
abi_stable = { version = "=0.11.3", default-features = false }
explorer-extension-api = { path = "../../../crates/explorer-extension-api", version = "=1.2.0" }
explorer-extension-ui-api = { path = "../../../crates/explorer-extension-ui-api", version = "=1.2.0" }

[profile.release]
panic = "unwind"
lto = "thin"
codegen-units = 1

[workspace]
