[package]
name = "extension-api-contract-old-v1-plugin"
version = "1.0.0"
edition = "2024"
rust-version = "1.97.1"
publish = false

[lib]
name = "extension_api_contract_old_v1_plugin"
crate-type = ["cdylib"]

[dependencies]
abi_stable = { version = "=0.11.3", default-features = false }
explorer-extension-api = { path = "../old-v1-api" }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[workspace]
