[CmdletBinding()]param([Parameter(Mandatory=$true)][ValidateSet('2.1.1','2.1.2','2.1.3','2.1.4','2.1.5','2.1.6','2.1.7')][string]$TaskId)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$dir=Join-Path $root "target/openspec-evidence/build-extensible-plugin-platform/$TaskId";New-Item -ItemType Directory -Force $dir|Out-Null
$commands=@{'2.1.1'=@('powershell','-NoProfile','-ExecutionPolicy','Bypass','-File','sdk/tests/toolchain-contract.ps1');'2.1.2'=@('powershell','-NoProfile','-ExecutionPolicy','Bypass','-File','sdk/tests/protected-dependency-contract.ps1');'2.1.4'=@('powershell','-NoProfile','-ExecutionPolicy','Bypass','-File','sdk/tests/toolchain-contract-self-test.ps1');'2.1.5'=@('powershell','-NoProfile','-ExecutionPolicy','Bypass','-File','sdk/tests/protected-dependency-contract-self-test.ps1');'2.1.6'=@('python','scripts/registry_provenance_audit.py','--root','.','--root','sdk');'2.1.7'=@('powershell','-NoProfile','-ExecutionPolicy','Bypass','-File','sdk/tests/protected-dependency-contract-self-test.ps1')}
Push-Location $root
try{
 if($TaskId-eq'2.1.3'){$command='cargo metadata --locked --offline --format-version 1 (root and sdk)';$rootGraph=& cargo metadata --locked --offline --format-version 1;if($LASTEXITCODE){throw 'root metadata failed'};Push-Location sdk;try{$sdkGraph=& cargo metadata --locked --offline --format-version 1;if($LASTEXITCODE){throw 'sdk metadata failed'}}finally{Pop-Location};$graphs=[ordered]@{root=($rootGraph|ConvertFrom-Json);sdk=($sdkGraph|ConvertFrom-Json)};[IO.File]::WriteAllText((Join-Path $dir 'resolved-graphs.json'),(($graphs|ConvertTo-Json -Depth 100 -Compress)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false));$code=0}
 else{$args=@($commands[$TaskId]);$exe=$args[0];$rest=@($args|Select-Object -Skip 1);$command=$args-join' ';&$exe @rest;$code=$LASTEXITCODE;if($null-eq$code){$code=0}}
 $rev=(&git rev-parse HEAD).Trim()
}finally{Pop-Location}
$report=[ordered]@{schema_version=1;task_id=$TaskId;procedure_kind='command';command=$command;cwd='.';environment=[ordered]@{validation_authority='local-only';uitest_executed='false';offline='true'};expected='exit code 0';actual=$(if($code-eq 0){'passed'}else{'failed'});exit_code=$code;source_revision=$rev;input_sha256=[ordered]@{}}
foreach($path in @('rust-toolchain.toml','Cargo.lock','sdk/rust-toolchain.toml','sdk/Cargo.lock','sdk/snapshot/protected-dependency-closure.json')){$report.input_sha256[$path]=(Get-FileHash -LiteralPath (Join-Path $root $path) -Algorithm SHA256).Hash.ToLowerInvariant()};if(Test-Path(Join-Path $dir 'resolved-graphs.json')){$report.input_sha256['resolved-graphs.json']=(Get-FileHash -LiteralPath (Join-Path $dir 'resolved-graphs.json') -Algorithm SHA256).Hash.ToLowerInvariant()}
$out=Join-Path $dir 'result.json';[IO.File]::WriteAllText($out,(($report|ConvertTo-Json -Depth 5)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false));Write-Output "REPORT $TaskId $((Get-FileHash -LiteralPath $out -Algorithm SHA256).Hash.ToLowerInvariant()) $out";if($code-ne 0){exit $code}
