[CmdletBinding()]param([Parameter(Mandatory=$true)][ValidatePattern('^2\.2\.([1-9]|1[0-6])$')][string]$TaskId)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$n=[int]$TaskId.Split('.')[2]
if($n-eq 1){$args=@('powershell','-NoProfile','-ExecutionPolicy','Bypass','-File','sdk/tests/gpui-baseline-contract.ps1')}
elseif($n-in @(2,3,6)){$args=@('powershell','-NoProfile','-ExecutionPolicy','Bypass','-File','sdk/tests/bundle-generator-contract.ps1')}
elseif($n-eq 5){$args=@('cargo','test','--manifest-path','sdk/tools/ui-abi-fingerprint/Cargo.toml','--locked','unrelated_host_build_id_is_not_an_input')}
else{$args=@('cargo','test','--manifest-path','sdk/tools/ui-abi-fingerprint/Cargo.toml','--locked','every_single_factor_changes_and_rejects')}
$exe=$args[0];$rest=@($args|Select-Object -Skip 1);$command=$args-join' ';Push-Location $root;try{&$exe @rest;$code=$LASTEXITCODE;if($null-eq$code){$code=0};$rev=(&git rev-parse HEAD).Trim()}finally{Pop-Location}
$dir=Join-Path $root "target/openspec-evidence/build-extensible-plugin-platform/$TaskId";New-Item -ItemType Directory -Force $dir|Out-Null;$report=[ordered]@{schema_version=1;task_id=$TaskId;procedure_kind='command';command=$command;cwd='.';environment=[ordered]@{validation_authority='local-only';uitest_executed='false'};expected='exit code 0';actual=$(if($code-eq 0){'passed'}else{'failed'});exit_code=$code;source_revision=$rev;input_sha256=[ordered]@{}}
foreach($path in @('sdk/sdk-lock.json','sdk/bundle-manifest.json','sdk/ui-abi-fingerprint.json','sdk/tools/ui-abi-fingerprint/src/lib.rs','sdk/tools/bundle-generator/src/lib.rs')){$report.input_sha256[$path]=(Get-FileHash -LiteralPath (Join-Path $root $path) -Algorithm SHA256).Hash.ToLowerInvariant()};$out=Join-Path $dir 'result.json';[IO.File]::WriteAllText($out,(($report|ConvertTo-Json -Depth 5)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false));Write-Output "REPORT $TaskId $((Get-FileHash -LiteralPath $out -Algorithm SHA256).Hash.ToLowerInvariant()) $out";if($code-ne 0){exit $code}
