$ErrorActionPreference='Stop';Import-Module (Join-Path $PSScriptRoot '..\scripts\update-gpui-snapshot-support.psm1') -Force
$o='a'*40;$n='b'*40;$t='c'*40;$d='d'*64;$run='42';$nonce='nonce';$now=[datetime]::UtcNow
$a=[pscustomobject]@{schema_version=1;baseline_revision=$o;old_revision=$o;new_revision=$n;new_tree=$t;candidate_tree_digest=$d;workflow_run_id=$run;nonce=$nonce;reason='test';approver='ci';issued_utc=$now.AddMinutes(-1).ToString('o');expires_utc=$now.AddHours(1).ToString('o')}
Assert-GpuiUpdateApproval $null $o $n $t $d $run $nonce $true $now|Out-Null;Assert-GpuiUpdateApproval $a $o $n $t $d $run $nonce $false $now|Out-Null
foreach($p in @('schema_version','baseline_revision','old_revision','new_revision','new_tree','candidate_tree_digest','workflow_run_id','nonce','reason','approver','issued_utc','expires_utc')){$b=$a.PSObject.Copy();$b.$p='';$ok=$false;try{Assert-GpuiUpdateApproval $b $o $n $t $d $run $nonce $false $now}catch{$ok=$true};if(!$ok){throw "missing/invalid accepted: $p"}}
$extra=$a.PSObject.Copy()|Add-Member x 1 -PassThru;$ok=$false;try{Assert-GpuiUpdateApproval $extra $o $n $t $d $run $nonce $false $now}catch{$ok=$true};if(!$ok){throw 'extra accepted'}
foreach($field in @('old_revision','new_revision','new_tree','candidate_tree_digest','workflow_run_id','nonce')){$b=$a.PSObject.Copy();$b.$field='f'*([int]$b.$field.Length);$ok=$false;try{Assert-GpuiUpdateApproval $b $o $n $t $d $run $nonce $false $now}catch{$ok=$true};if(!$ok){throw "identity replay accepted: $field"}}
$expired=$a.PSObject.Copy();$expired.expires_utc=$now.AddMinutes(-1).ToString('o');$future=$a.PSObject.Copy();$future.issued_utc=$now.AddMinutes(1).ToString('o');foreach($x in @($expired,$future)){$ok=$false;try{Assert-GpuiUpdateApproval $x $o $n $t $d $run $nonce $false $now}catch{$ok=$true};if(!$ok){throw 'timestamp drift accepted'}}
$tempRoot=Join-Path ([IO.Path]::GetTempPath()) ("superexplorer-gpui-transaction-"+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $tempRoot|Out-Null
try{$existing=Join-Path $tempRoot 'existing.bin';$created=Join-Path $tempRoot 'created.bin';$before=[byte[]](0,1,2,255);[IO.File]::WriteAllBytes($existing,$before);$failed=$false;try{Invoke-WithFileTransaction @($existing,$created) {[IO.File]::WriteAllText($existing,'changed');[IO.File]::WriteAllText($created,'created');throw 'injected failure'}}catch{$failed=$true};if(!$failed){throw 'transaction failure was swallowed'};if([Convert]::ToBase64String($before)-ne[Convert]::ToBase64String([IO.File]::ReadAllBytes($existing))){throw 'transaction rollback was not byte-identical'};if(Test-Path $created){throw 'transaction rollback retained a created file'};Invoke-WithFileTransaction @($existing) {[IO.File]::WriteAllText($existing,'committed')};if((Get-Content $existing -Raw)-ne'committed'){throw 'transaction commit was not retained'}}finally{Remove-Item -LiteralPath $tempRoot -Recurse -Force}
Write-Output 'gpui approval self-test passed'
